# See https://symfony.com/doc/current/email/dev_environment.html

swiftmailer:
  spool:     { type: memory }
  transport: smtp
  host:      smtp.mailtrap.io
  username:  91ba5da3d99a49
  password:  33c0d0765267ee
  auth_mode: cram-md5
  port: 2525
